### PR TITLE
DevEx Improvements and Bug Squashing

### PR DESCRIPTION
**Pull request by CyrusOfEden**

### CODE REVIEW

**Comment by CyrusOfEden** [comment]
@henrycunh not sure why it's 8 commits but the diff is very small

**Comment by CyrusOfEden** [comment]
#d187303 includes:

Bugs:
1. Appending empty CompletionMessages without the appropriate function_call context
2. Answer not containing function_result

Changes:
1. cursive.CursiveModel => cursive.CursiveLanguageModel

Improvements:
1. Functions and Pydantic BaseModels can now be passed directly as functions= or function_call=
   and
2. cursive.model.CursiveModel to support struct-generation a la jxnl instructor

**Comment by henrycunh** [comment]
Amazing, thanks for the contributions!

Do you want to write an example of the new improvements on the README?

**Comment by CyrusOfEden** [comment]
Updated the README!

**Comment by henrycunh** [comment]
Thanks @CyrusOfEden, amazing work!

**Comment by CyrusOfEden** [comment]
Ayyy awesome :) 

Wen new release? :P

**Pull request merged**
